//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod advertisements;
pub mod availability_slots;
pub mod device_tokens;
pub mod favorites;
pub mod featured_professionals;
pub mod portfolio_items;
pub mod professional_profile_categories;
pub mod professional_profiles;
pub mod quote_responses;
pub mod reviews;
pub mod service_categories;
pub mod service_requests;
pub mod unlocked_contacts;
pub mod users;
pub mod chat_messages;
pub mod subscription_plans;
