//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "professional_profiles")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub bio: Option<String>,
    pub years_experience: i32,
    pub hourly_rate: Decimal,
    pub service_radius_km: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub address: Option<String>,
    pub latitude: Option<Decimal>,
    pub longitude: Option<Decimal>,
    pub average_rating: Decimal,
    pub total_reviews: i32,
    pub subscription_status: String,
    pub subscription_end_date: Option<DateTimeWithTimeZone>,
    pub payment_gateway_customer_id: Option<String>,
    pub payment_gateway_subscription_id: Option<String>,
    pub subscription_plan: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::unlocked_contacts::Entity")]
    UnlockedContacts,
}

impl Related<super::unlocked_contacts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UnlockedContacts.def()
    }
}
