//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "unlocked_contacts")]
pub struct Model {
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub professional_profile_id: Uuid,
    pub client_id: Uuid,
    pub service_request_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::professional_profiles::Entity",
        from = "Column::ProfessionalProfileId",
        to = "super::professional_profiles::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ProfessionalProfiles,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ClientId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::professional_profiles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProfessionalProfiles.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}
